"""phase2_cards_sessions_pricing_updates

Revision ID: 140759ec5905
Revises: d35b59a30b7b
Create Date: 2026-08-25 17:55:00.535260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140759ec5905'
down_revision: Union[str, None] = 'd35b59a30b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'LOST', 'DAMAGED', name='cardstatus'), server_default='available', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_cards_card_code'), 'parking_cards', ['card_code'], unique=True)
    
    # Drop the old indexes before altering the table
    op.drop_index('idx_active_barcode', table_name='parking_sessions', sqlite_where=sa.text('exit_time IS NULL'))
    op.drop_index('ix_parking_sessions_card_barcode', table_name='parking_sessions')
    op.drop_index('ix_parking_sessions_ticket_number', table_name='parking_sessions')
    
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('card_code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'LOST_CARD', name='sessionstatus'), server_default='ACTIVE', nullable=False))
        batch_op.add_column(sa.Column('is_lost_card', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('lost_card_penalty_applied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_override_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_override_note', sa.Text(), nullable=True))
        
        batch_op.create_foreign_key('fk_sessions_cards', 'parking_cards', ['card_id'], ['id'])
        batch_op.create_foreign_key('fk_sessions_override_user', 'users', ['admin_override_by'], ['id'])
        
        batch_op.drop_column('card_barcode')
        batch_op.drop_column('ticket_number')

    # Create the new indexes after altering the table
    op.create_index('idx_active_card_id', 'parking_sessions', ['card_id'], unique=True, sqlite_where=sa.text('exit_time IS NULL'), postgresql_where=sa.text('exit_time IS NULL'))
    op.create_index(op.f('ix_parking_sessions_card_id'), 'parking_sessions', ['card_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_shift_id'), 'parking_sessions', ['shift_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_status'), 'parking_sessions', ['status'], unique=False)
    
    op.add_column('pricing_rules', sa.Column('lost_card_penalty', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'lost_card_penalty')
    
    op.drop_index(op.f('ix_parking_sessions_status'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_shift_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_card_id'), table_name='parking_sessions')
    op.drop_index('idx_active_card_id', table_name='parking_sessions', sqlite_where=sa.text('exit_time IS NULL'), postgresql_where=sa.text('exit_time IS NULL'))
    
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_barcode', sa.VARCHAR(length=50), nullable=False))
        
        batch_op.drop_constraint('fk_sessions_cards', type_='foreignkey')
        batch_op.drop_constraint('fk_sessions_override_user', type_='foreignkey')
        
        batch_op.drop_column('admin_override_note')
        batch_op.drop_column('admin_override_by')
        batch_op.drop_column('lost_card_penalty_applied')
        batch_op.drop_column('is_lost_card')
        batch_op.drop_column('status')
        batch_op.drop_column('card_code')
        batch_op.drop_column('card_id')

    op.create_index('ix_parking_sessions_ticket_number', 'parking_sessions', ['ticket_number'], unique=True)
    op.create_index('ix_parking_sessions_card_barcode', 'parking_sessions', ['card_barcode'], unique=False)
    op.create_index('idx_active_barcode', 'parking_sessions', ['card_barcode'], unique=True, sqlite_where=sa.text('exit_time IS NULL'))
    
    op.drop_index(op.f('ix_parking_cards_card_code'), table_name='parking_cards')
    op.drop_table('parking_cards')
    # ### end Alembic commands ###
