"""create initial schema

Revision ID: a71da5149d84
Revises: 
Create Date: 2026-08-25 02:40:19.974535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71da5149d84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('gate_number', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(role = 'operator' AND gate_number IS NOT NULL AND gate_number BETWEEN 1 AND 5) OR (role = 'admin' AND gate_number IS NULL)", name='ck_users_role_gate_consistency'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('payload_before', sa.Text(), nullable=True),
    sa.Column('payload_after', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('rate_per_hour', sa.Integer(), nullable=False),
    sa.Column('minimum_charge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('grace_period_mins', sa.SmallInteger(), server_default='15', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('gate_number', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('opening_cash_egp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('closing_cash_egp', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('card_barcode', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=True),
    sa.Column('gate_number', sa.SmallInteger(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pricing_rule_id', sa.Integer(), nullable=True),
    sa.Column('amount_charged', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', name='paymentmethod'), server_default='cash', nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('exit_operator_id', sa.Integer(), nullable=True),
    sa.Column('exit_shift_id', sa.Integer(), nullable=True),
    sa.Column('receipt_printed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exit_operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exit_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pricing_rule_id'], ['pricing_rules.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_barcode', 'parking_sessions', ['card_barcode'], unique=True, sqlite_where=sa.text('exit_time IS NULL'), postgresql_where=sa.text('exit_time IS NULL'))
    op.create_index(op.f('ix_parking_sessions_card_barcode'), 'parking_sessions', ['card_barcode'], unique=False)
    op.create_index(op.f('ix_parking_sessions_ticket_number'), 'parking_sessions', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_sessions_ticket_number'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_card_barcode'), table_name='parking_sessions')
    op.drop_index('idx_active_barcode', table_name='parking_sessions', sqlite_where=sa.text('exit_time IS NULL'), postgresql_where=sa.text('exit_time IS NULL'))
    op.drop_table('parking_sessions')
    op.drop_table('shifts')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
